# Generated by Django 3.0.3 on 2020-03-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CURDApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
