# Generated by Django 2.2.5 on 2020-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('empname', models.CharField(max_length=25)),
                ('salary', models.FloatField()),
                ('designation', models.TextField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
